### PR TITLE
Initial DBVN Questionnaire

### PR DESCRIPTION
**Pull request by tonilanec**
We should collectively add a statement into the constitution to prevent centralized power.

### CODE REVIEW

**Comment by xsttx** [comment]
@tonilanec the constitution is holocratic and the DBVN is open source, which are the prevention mechanism to centralized power. Meaning, as outlined in the constitution, that if you don't like the holon you're currently in, you're free to form a new one. Or you're free to fork the DBVN in its entirety and create a brand new one.

**Comment by xsttx** [comment]
Also, this is not a pull request, but a comment. The issues are used for comments.

**Comment by tonilanec** [comment]
thank you for letting me know about the pull requests v comments. new to github!

is there anything that would give someone the authority to say, revoke a transaction (etc) as we saw with the hf in ethereum?

**Comment by ETeissonniere** [comment]
@tonilanec @xsttx closing the pull request since this is more issue stuff

**Pull request closed without merging**
